from .haigc_prompt_node import NODE_CLASS_MAPPINGS as PROMPT_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as PROMPT_NAME_MAPPINGS
from .haigc_camera_node import NODE_CLASS_MAPPINGS as CAMERA_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as CAMERA_NAME_MAPPINGS
from .haigc_style_node import NODE_CLASS_MAPPINGS as STYLE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STYLE_NAME_MAPPINGS
from .haigc_video_camera_node import NODE_CLASS_MAPPINGS as VIDEO_CAMERA_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as VIDEO_CAMERA_NAME_MAPPINGS
from .haigc_text_builder_node import NODE_CLASS_MAPPINGS as TEXT_BUILDER_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as TEXT_BUILDER_NAME_MAPPINGS

NODE_CLASS_MAPPINGS = {**PROMPT_CLASS_MAPPINGS, **CAMERA_CLASS_MAPPINGS, **STYLE_CLASS_MAPPINGS, **VIDEO_CAMERA_CLASS_MAPPINGS, **TEXT_BUILDER_CLASS_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**PROMPT_NAME_MAPPINGS, **CAMERA_NAME_MAPPINGS, **STYLE_NAME_MAPPINGS, **VIDEO_CAMERA_NAME_MAPPINGS, **TEXT_BUILDER_NAME_MAPPINGS}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
