class HAIGC_StyleNode:
    # 1. Styles (风格) - Targeting ~200 popular styles
    styles_dict = {
        "无": "None",
        # Art Movements & Periods
        "文艺复兴 (Renaissance)": "Renaissance style",
        "巴洛克 (Baroque)": "Baroque style",
        "洛可可 (Rococo)": "Rococo style",
        "新古典主义 (Neoclassicism)": "Neoclassicism",
        "浪漫主义 (Romanticism)": "Romanticism",
        "印象派 (Impressionism)": "Impressionism",
        "后印象派 (Post-Impressionism)": "Post-Impressionism",
        "表现主义 (Expressionism)": "Expressionism",
        "新艺术运动 (Art Nouveau)": "Art Nouveau",
        "装饰艺术 (Art Deco)": "Art Deco",
        "立体主义 (Cubism)": "Cubism",
        "超现实主义 (Surrealism)": "Surrealism",
        "抽象表现主义 (Abstract Expressionism)": "Abstract Expressionism",
        "波普艺术 (Pop Art)": "Pop Art",
        "极简主义 (Minimalism)": "Minimalism",
        "包豪斯 (Bauhaus)": "Bauhaus style",
        "浮世绘 (Ukiyo-e)": "Ukiyo-e",
        "水墨画 (Ink Wash Painting)": "Ink Wash Painting",
        "工笔画 (Gongbi)": "Gongbi style",
        "赛博朋克 (Cyberpunk)": "Cyberpunk",
        "蒸汽朋克 (Steampunk)": "Steampunk",
        "柴油朋克 (Dieselpunk)": "Dieselpunk",
        "原子朋克 (Atompunk)": "Atompunk",
        "太阳朋克 (Solarpunk)": "Solarpunk",
        "生物朋克 (Biopunk)": "Biopunk",
        "哥特式 (Gothic)": "Gothic style",
        "维多利亚 (Victorian)": "Victorian style",
        "中世纪 (Medieval)": "Medieval style",
        "古埃及 (Ancient Egyptian)": "Ancient Egyptian style",
        "古希腊 (Ancient Greek)": "Ancient Greek style",
        "未来主义 (Futurism)": "Futurism",
        "野兽派 (Fauvism)": "Fauvism",
        "达达主义 (Dadaism)": "Dadaism",
        "构成主义 (Constructivism)": "Constructivism",
        "至上主义 (Suprematism)": "Suprematism",
        "形而上艺术 (Metaphysical Art)": "Metaphysical Art",
        "前拉斐尔派 (Pre-Raphaelite)": "Pre-Raphaelite Brotherhood",
        "象征主义 (Symbolism)": "Symbolism",
        "写实主义 (Realism)": "Realism",
        "社会写实主义 (Social Realism)": "Social Realism",
        "魔幻现实主义 (Magic Realism)": "Magic Realism",
        "精确主义 (Precisionism)": "Precisionism",
        "地方主义 (Regionalism)": "Regionalism",
        "欧普艺术 (Op Art)": "Op Art",
        "大地艺术 (Land Art)": "Land Art",
        "观念艺术 (Conceptual Art)": "Conceptual Art",
        "具体派 (Gutai)": "Gutai group",
        "激浪派 (Fluxus)": "Fluxus",
        "贫穷艺术 (Arte Povera)": "Arte Povera",
        "涂鸦艺术 (Graffiti Art)": "Graffiti Art",
        "街头艺术 (Street Art)": "Street Art",
        "新表现主义 (Neo-Expressionism)": "Neo-Expressionism",
        "低眉艺术 (Lowbrow/Pop Surrealism)": "Lowbrow Art",
        "蒸汽波 (Vaporwave)": "Vaporwave",
        "合成波 (Synthwave)": "Synthwave",
        "复古波 (Retrowave)": "Retrowave",
        "故障艺术 (Glitch Art)": "Glitch Art",
        "像素艺术 (Pixel Art)": "Pixel Art",
        "体素艺术 (Voxel Art)": "Voxel Art",
        "低多边形 (Low Poly)": "Low Poly",
        "矢量艺术 (Vector Art)": "Vector Art",
        "扁平化设计 (Flat Design)": "Flat Design",
        "拟物化设计 (Skeuomorphism)": "Skeuomorphism",
        "孟菲斯设计 (Memphis Design)": "Memphis Design",
        "迷幻艺术 (Psychedelic Art)": "Psychedelic Art",
        "分形艺术 (Fractal Art)": "Fractal Art",
        "曼陀罗 (Mandala)": "Mandala",
        "马赛克 (Mosaic)": "Mosaic",
        "彩色玻璃 (Stained Glass)": "Stained Glass",
        "剪纸 (Paper Cut)": "Paper Cut Art",
        "折纸 (Origami)": "Origami",
        "拼贴画 (Collage)": "Collage",
        "蒙太奇 (Montage)": "Montage",
        "蚀刻版画 (Etching)": "Etching",
        "木刻版画 (Woodcut)": "Woodcut",
        "利诺剪纸 (Linocut)": "Linocut",
        "石版画 (Lithography)": "Lithography",
        "丝网印刷 (Screen Printing)": "Screen Printing",
        "蓝晒法 (Cyanotype)": "Cyanotype",
        "达盖尔银版法 (Daguerreotype)": "Daguerreotype",
        "湿版摄影 (Tintype)": "Tintype",
        "宝丽来 (Polaroid)": "Polaroid",
        "lomo风格 (Lomo)": "Lomography",
        "鱼眼摄影 (Fisheye)": "Fisheye Lens",
        "移轴摄影 (Tilt-Shift)": "Tilt-Shift Photography",
        "红外摄影 (Infrared)": "Infrared Photography",
        "微距摄影 (Macro)": "Macro Photography",
        "显微摄影 (Microscopic)": "Microscopic Photography",
        "天文摄影 (Astrophotography)": "Astrophotography",
        "水下摄影 (Underwater)": "Underwater Photography",
        "航拍 (Aerial)": "Aerial Photography",
        "无人机摄影 (Drone)": "Drone Photography",
        "全景摄影 (Panorama)": "Panorama",
        "360度全景 (360-degree)": "360-degree view",
        "HDR摄影 (HDR)": "HDR Photography",
        "长曝光 (Long Exposure)": "Long Exposure",
        "双重曝光 (Double Exposure)": "Double Exposure",
        "光绘 (Light Painting)": "Light Painting",
        "黑白摄影 (Black and White)": "Black and White Photography",
        "单色摄影 (Monochrome)": "Monochrome Photography",
        "深褐调 (Sepia)": "Sepia Tone",
        "胶片颗粒 (Film Grain)": "Film Grain",
        "复古胶片 (Vintage Film)": "Vintage Film",
        "柯达胶片 (Kodak Portra)": "Kodak Portra",
        "富士胶片 (Fujifilm)": "Fujifilm",
        "电影感 (Cinematic)": "Cinematic",
        "大片感 (Blockbuster)": "Blockbuster style",
        "黑色电影 (Film Noir)": "Film Noir",
        "韦斯·安德森风格 (Wes Anderson)": "Wes Anderson style",
        "赛博朋克2077 (Cyberpunk 2077)": "Cyberpunk 2077 style",
        "吉卜力风格 (Studio Ghibli)": "Studio Ghibli style",
        "新海诚风格 (Makoto Shinkai)": "Makoto Shinkai style",
        "京阿尼风格 (Kyoto Animation)": "Kyoto Animation style",
        "迪士尼风格 (Disney)": "Disney style",
        "皮克斯风格 (Pixar)": "Pixar style",
        "梦工厂风格 (Dreamworks)": "Dreamworks style",
        "漫威漫画 (Marvel Comics)": "Marvel Comics style",
        "DC漫画 (DC Comics)": "DC Comics style",
        "美漫风格 (American Comic)": "American Comic style",
        "日漫风格 (Manga)": "Manga style",
        "韩漫风格 (Manhwa)": "Manhwa style",
        "绘本风格 (Storybook)": "Storybook style",
        "儿童画 (Children's Drawing)": "Children's Drawing",
        "蜡笔画 (Crayon)": "Crayon Drawing",
        "粉笔画 (Chalk)": "Chalk Drawing",
        "炭笔画 (Charcoal)": "Charcoal Drawing",
        "铅笔素描 (Pencil Sketch)": "Pencil Sketch",
        "钢笔画 (Ink Drawing)": "Ink Drawing",
        "圆珠笔画 (Ballpoint Pen)": "Ballpoint Pen Drawing",
        "马克笔画 (Marker)": "Marker Drawing",
        "水彩画 (Watercolor)": "Watercolor Painting",
        "油画 (Oil Painting)": "Oil Painting",
        "丙烯画 (Acrylic)": "Acrylic Painting",
        "水粉画 (Gouache)": "Gouache Painting",
        "粉彩画 (Pastel)": "Pastel Painting",
        "蛋彩画 (Tempera)": "Tempera Painting",
        "壁画 (Fresco)": "Fresco",
        "涂鸦 (Graffiti)": "Graffiti",
        "喷漆画 (Spray Paint)": "Spray Paint Art",
        "数字绘画 (Digital Painting)": "Digital Painting",
        "概念艺术 (Concept Art)": "Concept Art",
        "插画 (Illustration)": "Illustration",
        "矢量插画 (Vector Illustration)": "Vector Illustration",
        "3D渲染 (3D Render)": "3D Render",
        "C4D渲染 (Cinema 4D)": "Cinema 4D render",
        "Blender渲染 (Blender)": "Blender render",
        "虚幻引擎 (Unreal Engine)": "Unreal Engine 5",
        "Unity引擎 (Unity)": "Unity Engine",
        "辛烷渲染 (Octane Render)": "Octane Render",
        "红移渲染 (Redshift)": "Redshift Render",
        "V-Ray渲染 (V-Ray)": "V-Ray Render",
        "阿诺德渲染 (Arnold)": "Arnold Render",
        "光线追踪 (Ray Tracing)": "Ray Tracing",
        "全局光照 (Global Illumination)": "Global Illumination",
        "体积光 (Volumetric Lighting)": "Volumetric Lighting",
        "焦散 (Caustics)": "Caustics",
        "次表面散射 (Subsurface Scattering)": "Subsurface Scattering",
        "环境光遮蔽 (Ambient Occlusion)": "Ambient Occlusion",
        "景深 (Depth of Field)": "Depth of Field",
        "运动模糊 (Motion Blur)": "Motion Blur",
        "色差 (Chromatic Aberration)": "Chromatic Aberration",
        "光晕 (Bloom)": "Bloom",
        "镜头光晕 (Lens Flare)": "Lens Flare",
        "晕影 (Vignette)": "Vignette",
        "噪点 (Noise)": "Noise",
        "故障效果 (Glitch)": "Glitch effect",
        "半色调 (Halftone)": "Halftone",
        "点阵图 (Dithering)": "Dithering",
        "ASCII艺术 (ASCII Art)": "ASCII Art",
        "文本艺术 (Text Art)": "Text Art",
        "表情符号艺术 (Emoji Art)": "Emoji Art",
        "乐高风格 (Lego)": "Lego style",
        "我的世界风格 (Minecraft)": "Minecraft style",
        "罗布乐思风格 (Roblox)": "Roblox style",
        "堡垒之夜风格 (Fortnite)": "Fortnite style",
        "守望先锋风格 (Overwatch)": "Overwatch style",
        "英雄联盟风格 (League of Legends)": "League of Legends style",
        "魔兽世界风格 (World of Warcraft)": "World of Warcraft style",
        "艾尔登法环风格 (Elden Ring)": "Elden Ring style",
        "黑暗之魂风格 (Dark Souls)": "Dark Souls style",
        "血源诅咒风格 (Bloodborne)": "Bloodborne style",
        "塞尔达风格 (Zelda)": "Legend of Zelda style",
        "马里奥风格 (Mario)": "Super Mario style",
        "宝可梦风格 (Pokemon)": "Pokemon style",
        "数码宝贝风格 (Digimon)": "Digimon style",
        "高达风格 (Gundam)": "Gundam style",
        "变形金刚风格 (Transformers)": "Transformers style",
        "星球大战风格 (Star Wars)": "Star Wars style",
        "星际迷航风格 (Star Trek)": "Star Trek style",
        "指环王风格 (Lord of the Rings)": "Lord of the Rings style",
        "哈利波特风格 (Harry Potter)": "Harry Potter style",
        "权力的游戏风格 (Game of Thrones)": "Game of Thrones style",
        "沙丘风格 (Dune)": "Dune style",
        "银翼杀手风格 (Blade Runner)": "Blade Runner style",
        "黑客帝国风格 (The Matrix)": "The Matrix style",
        "疯狂的麦克斯风格 (Mad Max)": "Mad Max style",
        "异形风格 (Alien)": "Alien style",
        "铁血战士风格 (Predator)": "Predator style",
        "终结者风格 (Terminator)": "Terminator style",
        "生化危机风格 (Resident Evil)": "Resident Evil style",
        "寂静岭风格 (Silent Hill)": "Silent Hill style",
        "克苏鲁风格 (Lovecraftian)": "Lovecraftian style",
        "SCP风格 (SCP)": "SCP Foundation style",
        "后室风格 (Backrooms)": "The Backrooms style",
        "梦核 (Dreamcore)": "Dreamcore",
        "怪核 (Weirdcore)": "Weirdcore",
        "伤感核 (Traumacore)": "Traumacore",
        "村舍核 (Cottagecore)": "Cottagecore",
        "暗黑学院 (Dark Academia)": "Dark Academia",
        "光亮学院 (Light Academia)": "Light Academia",
        "仙女核 (Fairycore)": "Fairycore",
        "哥布林核 (Goblincore)": "Goblincore",
        "太空核 (Spacecore)": "Spacecore",
        "Y2K风格 (Y2K)": "Y2K aesthetic",
        "90年代风格 (90s)": "90s aesthetic",
        "80年代风格 (80s)": "80s aesthetic",
        "70年代风格 (70s)": "70s aesthetic",
        "60年代风格 (60s)": "60s aesthetic",
        "50年代风格 (50s)": "50s aesthetic",
        "维多利亚时代 (Victorian Era)": "Victorian Era",
        "爱德华时代 (Edwardian Era)": "Edwardian Era",
        "咆哮的二十年代 (Roaring Twenties)": "Roaring Twenties",
        "大萧条时期 (Great Depression)": "Great Depression era",
        "二战时期 (WWII Era)": "WWII Era",
        "冷战时期 (Cold War Era)": "Cold War Era",
        "原子时代 (Atomic Age)": "Atomic Age",
        "太空竞赛 (Space Age)": "Space Age",
        "信息时代 (Information Age)": "Information Age"
    }

    # 2. Composition (构图)
    composition_dict = {
        "无": "None",
        "三分法 (Rule of Thirds)": "Rule of Thirds",
        "黄金比例 (Golden Ratio)": "Golden Ratio",
        "中心构图 (Center Composition)": "Center Composition",
        "对称构图 (Symmetrical Composition)": "Symmetrical Composition",
        "非对称构图 (Asymmetrical Composition)": "Asymmetrical Composition",
        "对角线构图 (Diagonal Composition)": "Diagonal Composition",
        "引导线 (Leading Lines)": "Leading Lines",
        "框架构图 (Framing)": "Framing",
        "负空间 (Negative Space)": "Negative Space",
        "极简构图 (Minimalist Composition)": "Minimalist Composition",
        "填充画面 (Fill the Frame)": "Fill the Frame",
        "图案与纹理 (Patterns and Textures)": "Patterns and Textures",
        "奇数法则 (Rule of Odds)": "Rule of Odds",
        "空间感 (Sense of Space)": "Sense of Space",
        "透视 (Perspective)": "Perspective",
        "一点透视 (One Point Perspective)": "One Point Perspective",
        "两点透视 (Two Point Perspective)": "Two Point Perspective",
        "三点透视 (Three Point Perspective)": "Three Point Perspective",
        "鱼眼透视 (Fisheye Perspective)": "Fisheye Perspective",
        "等距透视 (Isometric Perspective)": "Isometric Perspective",
        "空气透视 (Aerial Perspective)": "Aerial Perspective",
        "前景 (Foreground)": "Foreground focus",
        "背景 (Background)": "Background focus",
        "景深 (Depth)": "Depth",
        "层次感 (Layering)": "Layering",
        "动态构图 (Dynamic Composition)": "Dynamic Composition",
        "静态构图 (Static Composition)": "Static Composition",
        "平衡 (Balance)": "Balanced Composition",
        "对比 (Contrast)": "High Contrast Composition"
    }

    # 3. Optimization/Quality (优化/画质)
    optimization_dict = {
        "无": "None",
        "大师级作品 (Masterpiece)": "Masterpiece, best quality, highly detailed",
        "8K超高清 (8K UHD)": "8k, uhd, high resolution",
        "极致细节 (Insane Details)": "intricate details, hyperdetailed, sharp focus",
        "电影级光效 (Cinematic Lighting)": "cinematic lighting, dramatic lighting, volumetric lighting",
        "照片级真实 (Photorealistic)": "photorealistic, realistic, raw photo",
        "虚幻引擎5 (Unreal Engine 5)": "Unreal Engine 5 render, octane render, ray tracing",
        "获奖作品 (Award Winning)": "award winning, trending on artstation, featured on pixiv",
        "完美构图 (Perfect Composition)": "perfect composition, golden ratio",
        "色彩增强 (Vivid Colors)": "vivid colors, vibrant, color grading",
        "HDR高动态 (HDR)": "HDR, high dynamic range",
        "无损画质 (Lossless)": "lossless quality, 4k texture",
        "工作室质量 (Studio Quality)": "studio quality, professional",
        "清晰面部 (Detailed Face)": "detailed face, beautiful face, perfect eyes",
        "平滑渲染 (Smooth)": "smooth rendering, anti-aliasing",
        "高对比度 (High Contrast)": "high contrast, sharp",
        "壁纸画质 (Wallpaper)": "wallpaper quality, official art",
        "概念艺术 (Concept Art)": "concept art, detailed painting"
    }

    # 4. Color Tones (色调)
    color_dict = {
        "无": "None",
        "暖色调 (Warm)": "warm tones, orange and yellow hues",
        "冷色调 (Cool)": "cool tones, blue and teal hues",
        "中性色 (Neutral)": "neutral colors, desaturated",
        "鲜艳 (Vibrant)": "vibrant colors, saturated",
        "柔和 (Pastel)": "pastel colors, soft tones",
        "黑白 (B&W)": "black and white, monochrome, greyscale",
        "复古 (Vintage)": "vintage colors, sepia, faded",
        "赛博朋克 (Cyberpunk)": "neon colors, cyberpunk palette, pink and blue",
        "蒸汽波 (Vaporwave)": "vaporwave palette, purple and teal",
        "哥特 (Gothic)": "dark colors, black and red, gloomy",
        "自然 (Earth Tones)": "earth tones, green and brown",
        "黄金时刻 (Golden Hour)": "golden hour colors, sunset hues",
        "蓝调时刻 (Blue Hour)": "blue hour colors, twilight",
        "高对比度 (High Contrast)": "high contrast colors",
        "低对比度 (Low Contrast)": "low contrast colors, flat"
    }

    def __init__(self):
        pass
    
    @classmethod
    def INPUT_TYPES(s):
        return {
            "required": {
                "风格": (list(s.styles_dict.keys()), {"default": "无"}),
                "构图": (list(s.composition_dict.keys()), {"default": "无"}),
                "画质优化": (list(s.optimization_dict.keys()), {"default": "无"}),
                "色调": (list(s.color_dict.keys()), {"default": "无"}),
            }
        }

    RETURN_TYPES = ("STRING",)
    RETURN_NAMES = ("prompt",)
    FUNCTION = "generate_style_prompt"
    CATEGORY = "HAIGC/Prompt"

    def generate_style_prompt(self, 风格, 构图, 画质优化, 色调):
        # Helper to lookup English part
        def get_en(val, mapping):
            if val and val != "无":
                return mapping.get(val, None)
            return None

        style_en = get_en(风格, self.styles_dict)
        comp_en = get_en(构图, self.composition_dict)
        opt_en = get_en(画质优化, self.optimization_dict)
        color_en = get_en(色调, self.color_dict)

        parts = []
        if style_en:
            parts.append(style_en)
        if comp_en:
            parts.append(comp_en)
        if opt_en:
            parts.append(opt_en)
        if color_en:
            parts.append(color_en)
            
        result = ", ".join(parts)
        return (result,)

# Node mappings
NODE_CLASS_MAPPINGS = {
    "HAIGC_StyleNode": HAIGC_StyleNode
}

NODE_DISPLAY_NAME_MAPPINGS = {
    "HAIGC_StyleNode": "提示词风格"
}
